version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: kario_db
    environment:
      MARIADB_ROOT_PASSWORD: Alumno@2024
      MYSQL_DATABASE: kario_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: